baseURL: "https://srinijad.netlify.app/"
languageCode: "en-us"
title: "Srinija Dharani"
theme: "./.."
relativeURLs: true

googleanalytics: UA-167646412-8
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true

# menus
Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blog
      weight: 1

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /ew
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /34545
    #   parent: dropdown
    #   weight: 2

params:
  version: 3
  customCSS: false
  favicon: ""

  # home
  disable_home: false
  profile_image: "/images/profile-srinija.jpg"
  name: "Srinija Dharani"
  namecolor: 007bff
  github: "https://github.com/srinijadharani"
  linkedin: "https://www.linkedin.com/in/srinijadharani/"
  
  customSocialLinks:
    - fontAwesomeIconName: "fa fa-envelope"
      url: "dharanisrinija@gmail.com"
  
  # About
  disable_about: false
  descripe_l1_person: "Not your usual data science enthusiast. I am a total data fanatic; with so much data available, I love deriving valuable insights. I clean and analyse data for fun. I love mathematics as well. Since data science and machine learning use math extensively, I enjoy exploring and studying data even more! I also like working on artificial neural networks and natural language processing. I code primarily in Python."
  descripe_l2_person: "I have experience developing front-end websites, and I've designed websites for two student clubs in my college. I also have managerial experience; I was successful in helping build two student bodies in the past that are now fully functioning independently. You can find my works [here](#projects)."
  skills:
  - name: Data Science
    percentage: 90
  - name: Machine Learning
    percentage: 95
  - name: Computer Vision
    percentage: 95
  - name: Deep Learning
    percentage: 80
  - name: Data Structures & Algorithms
    percentage: 85
    
  # Experience
  disable_experience: false
  experience:
    - company: "GitHub"
      # id: "google-developer"   // use this, when you want to change the id(used for navigation)
      role: "Campus Expert"
      startdate: Oct 2021
      enddate: present
      featuredpoints:
        - point: Building an active and thriving technical community on campus for like-minded people and bring awareness among people about how technology could significantly impact people's lives in the coming future.
        - point: Handling the AIML domain of the community.
    - company: "GITAM"
      # id: "facebook-developer" // use this, when you want to change the id(used for navigation)
      role: "Student Life Associate"
      startdate: Nov 2021
      enddate: present
      featuredpoints:
        - point: As an SLA, I develop and maintain collaborative relationships with all the clubs and special interest groups (SIGs) on campus.
    - company: "Microsoft"
      # id: "facebook-developer" // use this, when you want to change the id(used for navigation)
      role: "Beta Ambassador"
      startdate: Jan 2021
      enddate: Dec 2021
      featuredpoints:
        - point: Conducted a workshop on hosting a website on Azure App Services.
        - point: Helped a few Alpha Ambassadors in conducting their events.
  
  # Education
  disable_education: false
  education:
    - degree: "B.tech"
      branch: "Computer Science and Engineering"
      university: "GITAM Univeristy, Bangalore | 9.53"
      startedyear: "2019"
      graduation: "2023"
    - degree: "Pre-university"
      branch: "CBSE Board"
      university: "Sri Chaitanya Techno School | 87%"
      startedyear: "2017"
      graduation: "2019"
    - degree: "High School"
      branch: "CBSE Board"
      university: "Chinmaya Vidyalaya | 10"
      startedyear: "2013"
      graduation: "2017"

  # Projects
  disable_projects: false
  projects:
    - name: "Chrome Dinosaur Game"
      img: /images/chrome.png
      githublink: "https://github.com/srinijadharani/Chrome_Dinosaur_Game"
      featuredlink: "https://analyticsindiamag.com/how-i-played-the-chrome-dino-game-with-just-my-palm/"
      description: "Description of project"
    - name: "E-Commerce Purchase Analysis"
      img: /images/ecommerce.jpg
      githublink: "https://github.com/srinijadharani/Python-Projects/tree/main/E-Commerce%20Purchase%20Analysis"
      featuredlink: "/"
      description: "EDA of all e-commerce purchases using a dataset."
    - name: "Face Mask Detection"
      img: /images/mask.png
      githublink: "https://github.com/srinijadharani/Python-Projects/tree/main/Face%20Mask%20Detection"
      featuredlink: "/"
      description: "This model detects whether you've worn a mask or not."
    - name: "Book Recommendation System"
      img: /images/book.png
      githublink: "https://github.com/srinijadharani/Book-Recommendation-System"
      featuredlink: "/"
      description: "This recommender system recommends similar books to the reader based on his/her interest."

  disable_achievements: true
  # Contact
  disable_contact: false
  contact_content: If you want to talk about Harry Potter or buy me a coffee, write to me here. My inbox is always open!
  email: "dharanisrinija@gmail.com"

  # Footer
  socialiconfooter: true
  recentposts: true

  # Blog
  showdescription: false
  tweet: true
