baseURL: "https://srinijad.netlify.app/"
languageCode: "en-us"
title: "Srinija Dharani"
theme: "./.."
relativeURLs: true

googleanalytics: UA-167646412-8
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true

# menus
Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blog
      weight: 1

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /ew
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /34545
    #   parent: dropdown
    #   weight: 2

params:
  version: 3
  customCSS: false
  favicon: ""

  # home
  disable_home: false
  profile_image: "/images/profile.png"
  name: "Srinija Dharani"
  namecolor: ffc107
  github: "https://github.com/srinijadharani"
  linkedin: "https://www.linkedin.com/in/srinijadharani/"
  instagram: "https://www.instagram.com/srinija.dharani/"

  #Custom social links
  # customSocialLinks:
  #   - imageURL: "https://hugo-profile.netlify.app/images/fav.png"
  #     url: "https://gohugo.com"
  #   - fontAwesomeIconName: "fa fa-envelope"
  #     url: "https://gmail.com"
  
  # About
  disable_about: false
  descripe_l1_person: "Hi! I'm Srinija. I'm a student at GITAM University, Bangalore, pursuing bachelors in technology, majoring in computer science and engineering."
  descripe_l2_person: "You can find my works [here](#projects)"
  skills:
  - name: Data Science
    percentage: 90
  - name: Machine Learning
    percentage: 95
  - name: Computer Vision
    percentage: 95
  - name: Deep Learning
    percentage: 80
  - name: Data Structures & Algorithms
    percentage: 85
  # Experience
  disable_experience: false
  experience:
    - company: "Yahoo!"
      # id: "google-developer"   // use this, when you want to change the id(used for navigation)
      role: "Software developer"
      startdate: Feb 2021
      enddate: present
      featuredpoints:
        - point: Lead backend developer for a product.
        - point: Created a frontend design for a product.
    - company: "Facebook"
      # id: "facebook-developer" // use this, when you want to change the id(used for navigation)
      role: "Fullstack developer"
      startdate: Mar 2020
      enddate: Dec 2020
      featuredpoints:
        - point: Lead backend developer for a product.
        - point: Created a frontend design for a product.
    - company: "Amazon"
      # id: "amazon-developer" // use this, when you want to change the id(used for navigation)
      role: "Fullstack developer"
      startdate: Feb 2019
      enddate: Jan 2020
      featuredpoints:
        - point: Lead backend developer for a product.
        - point: Created a frontend design for a product.

  # Education
  disable_education: false
  education:
    - degree: "B.tech"
      branch: "Information Technology"
      university: "Example university"
      startedyear: "2013"
      graduation: "2018"
    - degree: "Degree"
      branch: "Branch"
      university: "Example university"
      startedyear: "year"
      graduation: "year"
    - degree: "Degree"
      branch: "Branch"
      university: "Example university"
      startedyear: "year"
      graduation: "year"

  # Projects
  disable_projects: false
  projects:
    - name: "Example project without details"
      img: /images/project.jpg
      githublink: "https://github.com/"
      featuredlink: "/"
      description: "Description of project"

  # Achievements
  disable_achievements: false
  achievements:
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
      url: https://example.com
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
      # url: https://example.com
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg

  # Contact
  disable_contact: false
  contact_content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!
  email: "example@mail.com"

  # Footer
  socialiconfooter: true
  recentposts: true

  # Blog
  showdescription: false
  tweet: true
